# Generated by Django 5.0 on 2026-07-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About Us', max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('list_item_1', models.CharField(blank=True, max_length=100)),
                ('list_item_2', models.CharField(blank=True, max_length=100)),
                ('list_item_3', models.CharField(blank=True, max_length=100)),
                ('button_text', models.CharField(default='Contact Us', max_length=50)),
                ('button_url', models.CharField(default='/', max_length=200)),
                ('image_1', models.ImageField(upload_to='about/')),
                ('image_2', models.ImageField(upload_to='about/')),
                ('image_3', models.ImageField(upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Why Choose Us', max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='chooseus/')),
                ('emergency_label', models.CharField(default='For Emergency', max_length=50)),
                ('emergency_phone', models.CharField(max_length=30)),
                ('button_text', models.CharField(default='Contact Us', max_length=50)),
                ('button_url', models.CharField(default='/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Choose Us Section',
                'verbose_name_plural': 'Choose Us Section',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='cta/')),
                ('heading', models.CharField(max_length=200)),
                ('button_1_text', models.CharField(default='Contact Us', max_length=50)),
                ('button_1_url', models.CharField(default='/', max_length=200)),
                ('button_2_text', models.CharField(default='Get a Quotes', max_length=50)),
                ('button_2_url', models.CharField(default='/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='e.g. icon-8 (from theme font-icons)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_url', models.CharField(default='/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField(help_text='e.g. 20')),
                ('suffix', models.CharField(blank=True, help_text='e.g. k, +, 5k', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text='e.g. Waste Management', max_length=100)),
                ('heading', models.CharField(help_text='e.g. Reliable waste collection across Dhaka', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banner/')),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('button_url', models.CharField(default='/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('post_date', models.DateField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('link_url', models.CharField(default='/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(default='Waste Pickup', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.CharField(default='/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecycleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('icon_class', models.CharField(help_text='e.g. icon-12', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_url', models.CharField(default='/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='testimonials/')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChooseUsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.chooseussection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
